// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxYvPtLtBrvN1UCXHG8Eltqe294R6Wi5c',
    appId: '1:135885808423:web:9ea57360530f466e51bf02',
    messagingSenderId: '135885808423',
    projectId: 'horizon-3e51e',
    authDomain: 'horizon-3e51e.firebaseapp.com',
    storageBucket: 'horizon-3e51e.appspot.com',
    measurementId: 'G-YHTGGSMPB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6N-QUfaIoj2M7WAaadZ9CwWl6Kms9MY',
    appId: '1:135885808423:android:ec7b1ba68d03c67451bf02',
    messagingSenderId: '135885808423',
    projectId: 'horizon-3e51e',
    storageBucket: 'horizon-3e51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaz_T3nqP9JO-d4qUDMdCPM2XU2ZuUfg',
    appId: '1:135885808423:ios:c2f6036dfe72930951bf02',
    messagingSenderId: '135885808423',
    projectId: 'horizon-3e51e',
    storageBucket: 'horizon-3e51e.appspot.com',
    iosBundleId: 'com.example.horizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaz_T3nqP9JO-d4qUDMdCPM2XU2ZuUfg',
    appId: '1:135885808423:ios:c2f6036dfe72930951bf02',
    messagingSenderId: '135885808423',
    projectId: 'horizon-3e51e',
    storageBucket: 'horizon-3e51e.appspot.com',
    iosBundleId: 'com.example.horizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxYvPtLtBrvN1UCXHG8Eltqe294R6Wi5c',
    appId: '1:135885808423:web:204c8192dd958ae551bf02',
    messagingSenderId: '135885808423',
    projectId: 'horizon-3e51e',
    authDomain: 'horizon-3e51e.firebaseapp.com',
    storageBucket: 'horizon-3e51e.appspot.com',
    measurementId: 'G-7Q5LLJBX77',
  );
}
